// @flow
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_FAILURE = 'LOAD_QUESTIONS_FAILURE';
export const CHANGE_QUESTIONS = 'CHANGE_QUESTIONS';
export const CHANGE_QUESTIONS_SUCCESS = 'CHANGE_QUESTIONS_SUCCESS';
export const CHANGE_QUESTIONS_FAILURE = 'CHANGE_QUESTIONS_FAILURE';
